version: '3'
services:
  pyspark-jupyter:
    image: jupyter/pyspark-notebook
    container_name: pyspark-jupyter-container
    ports:
      - "8888:8888"
      - "4040:4040"    # Spark UI port
    volumes:
      - "./spark:/home/jovyan/work/notebooks"
      - "./data:/home/jovyan/work/notebooks/datasets"
    command: start-notebook.sh --NotebookApp.token=''
